# inventory file generated for all-in-one openshift cluster with ocp metrics
# located under /var/lib/origin/openshift.local.config/metrics.inventory
#
[OSEv3:children]
masters
nodes

[OSEv3:vars]
#openshift_release=v3.6.1
ansible_ssh_user=root
openshift_deployment_type=origin
openshift_image_tag=v3.6.1

openshift_metrics_install_metrics=true
openshift_metrics_image_prefix=openshift/origin-
openshift_metrics_image_version=v3.6.1
openshift_metrics_resolution=10s

openshift_metrics_hawkular_hostname=hawkular-metrics-openshift-infra.PUBIP.nip.io
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/var/lib/origin/openshift-passwd'}]
openshift_hostname=PUBIP
openshift_public_hostname=master.PUBIP.nip.io
openshift_master_default_subdomain=paas.master.PUBIP.nip.io
openshift_disable_check=disk_availability,memory_availability
debug_level=4
containerized=true
openshift_use_etcd_system_container=true
os_firewall_use_firewalld=true
# Cloud provider config
#
openshift_cloudprovider_kind=aws
openshift_cloudprovider_aws_secret_key=W+SwC/UOVC9l3Qk2wSdogS5Spu2vQ2XKDOaobsxR
openshift_cloudprovider_access_key=AKIAIF7A45F2OWAINIYQ

[masters]
PUBIP openshift_hostname=master openshift_public_hostname=master.PUBIP.nip.io ansible_connection=local openshift_schedulable=true containerized=true

[nodes]
INTERNAL openshift_hostname=node1 openshift_public_hostname=node1.INTERNAL.nip.io openshift_schedulable=true containerized=true openshift_node_labels="{'region': 'infra'}"
